### ISSUE TITLE
Questions about this repository

### ISSUE THREAD

**Issue by Milleupup** [boschresearch/cuae-prediction#1]
I'm curious when you will be able to complete this code repository, as it has been two months already.

**Comment by farisjanjos** [comment]
Hi, sorry that it's taking so long. We are currently in the process of getting the necessary approvals and hope to have the code online early next year. If you need help reproducing the approaches, feel free to reach out via email (faris.janjos@de.bosch.com), we'd be happy to help. Also, feel free to check out the [code of our base UAE model](https://github.com/boschresearch/unscented-autoencoder) for the main ideas behind the CUAE.

**Comment by Milleupup** [comment]
您好，您的邮件我已收到，稍后会给您回复，谢谢！
