### ISSUE TITLE
 some problems

### ISSUE THREAD

**Issue by ccbbzz** [boschresearch/cuae-prediction#2]
Hello! I encountered some issues when running the first command in "Rollouts".
![微信截图_20240419191806](https://github.com/boschresearch/cuae-prediction/assets/136176843/2862291d-9d83-4097-95b2-fbf205ff9a76)
![微信截图_20240419191834](https://github.com/boschresearch/cuae-prediction/assets/136176843/087cd9f0-7230-4f31-b975-1d20152bab70)

**Comment by farisjanjos** [comment]
Hi, you probably did not run `pip install -e .` since the module paths are not resolved.
