### ISSUE TITLE
Question about INTERACTION leader board

### ISSUE THREAD

**Issue by kkk00714** [boschresearch/cuae-prediction#3]
@farisjanjos Hello, I would like to know if the data for MB-SS-ASP on the INTERACTION leaderboard single-agent track is based on all types of scenarios or only on regular types. Up to the end of 2023, all methods only included data for all types. However, I found that when I only submit regular data, it still generates data for all types. This makes me wonder about the scores of previous methods.

**Comment by farisjanjos** [comment]
Hi, we submitted based on `all` types -- our method anyway does not show up on the leaderboard for `regular`.
